# Build settings for Netlify
[build]
  # This tells Netlify where to find your functions
  functions = "netlify/functions"

# Redirects for your API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
